#!/usr/bin/env escript
%% -*- erlang -*-

main([Src, Dest])->
  {ok, [Terms]} = file:consult(Src),
  Url = os:getenv("DATABASE_URL"),
  Password = os:getenv("ADMIN_PASSWORD"),
  Dict = dict:from_list(Terms),
  {ok, {postgres, UserPass, Host, Port, [$/ | DbName], _}} = http_uri:parse(Url),
  [User, Pass] = string:tokens(UserPass, ":"),
  Params = [{dbhost, Host}, {dbport, Port}, {dbuser, User},
            {dbpass, Pass}, {dbdatabase, DbName}, {hostname, none}, 
            {admin_password, Password}],
  Configured = lists:foldl(fun({K, V}, Acc)->
    dict:store(K, V, Acc)
  end, Dict, Params),
  {ok, S} = file:open(Dest, write),
  io:format(S, "~p.", [dict:to_list(Configured)]);

main(_)->
  io:format("usage: zotonic_config <src_config_file> <destination_config_file>~n").
